baseurl      = "https://goonie.onrender.com"
title        = "UI Hexed"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

    [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = ["for the &#10084; of simplicity",
      "Written in neovim"
    ]

  # Subtitle for home
  homeSubtitle = "My Profile Page"

  description = "As i pass through the computer science route"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

[author]
  name = "Prince Mwase"
  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"

  [[menu.main]]
    identifier = "About"
    name       = "About"
    url        = "about/"

  [[menu.main]]
    identifier = "Projects"
    name       = "Projects"
    url        = "projects/"

    
[[params.social]]
  name = "github"
  url = "https://github.com/PrinceMwase"

[[params.social]]
  name = "email"
  url = "mailto://princefranklinemwase@gmail.com"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/prince-mwase-986356b0/"

[[params.social]]
  name = "whatsapp"
  url = "https://wa.me/+265884652513"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/MwaseSparrow"

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd Prince/home/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
  [params.portrait]
     path     = "/img/image.jpg"
     alt      = "Portrait"
     maxWidth = "50px"